name: deploy-production

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy_a_bundle_to_production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "deploy a bundle job for production"

  deploy_b_bundle_to_production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "deploy b bundle job for production"
